FROM node:20-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code
COPY . .

# Build Next.js pour la production
RUN npm run build

# Exposer le port
EXPOSE 3000

# Commande de démarrage (production)
CMD ["npm", "start"]
